sudo: required
language: python
python:
    - "2.7"
    - "3.4"
    - "3.5"
    - "3.6"

install:
  - cd ${TRAVIS_BUILD_DIR}
  - pip install --upgrade pip
  - pip install .
  - pip install codecov pytest pytest-cov cookiecutter

script:
  - python -m pytest --cov=r_lint .
  - cookiecutter --no-input https://github.com/qbicsoftware/r-container-template
  - r-lint lint .

after_success:
  - codecov